#!/bin/sh

dest=$(cat DIR)
script=$(cat SYNC_SCRIPT_PATH)
filename="$(./genurl).txt"
url="$(cat URL)/$filename"

[ -z "$1" ] && tee -a "$dest/$filename" > /dev/null && sh "$script" || cp --no-preserve=all "$1" "$dest/$filename" && sh "$script"

echo "Done!"
echo "site available at $url"
